services:
  web:
    container_name: openai-flask-starter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT}:5000
    volumes:
      - .:/app
    env_file:
      - .env
